### ISSUE TITLE
Update documentation re: pip install --no-use-wheel --download

### ISSUE THREAD

**Issue by rm511130** [Pivotal-Field-Engineering/ephemerol#13]
The following command described in the installation instructions:

### _pip install --no-use-wheel --download ./ephemerol/vendor -r requirements.txt_ 

did not work for me on my MacBook. I got the following deprecation messages:

### _DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead._

Per the deprecation messages, I tried the following command and it did work:

### _pip download --no-binary ./ephemerol/vendor -r requirements.txt_

I propose that the installation instructions be updated.

**Comment by jwilliams-pivotal** [comment]
This change has been added to the Readme. Thank you for providing the suggestion!
