### ISSUE TITLE
OS X El Capitan comptability

### ISSUE THREAD

**Issue by anwarchk** [Pivotal-Field-Engineering/ephemerol#7]
Is this only supposed to work on Linux ? I tried to run this on a Mac with Python 2.7.12 installed and is getting error for `python ./ephemerol/ephemerol-web.py`

```
Traceback (most recent call last):
  File "./ephemerol/ephemerol-web.py", line 16, in <module>
    from flask import render_template, Flask, request, Response, flash
  File "/usr/local/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request`
```
Similar issues with the other commands from README.

**Comment by mcowger** [comment]
Sounds like you dont have the requirements installed.  You'll need to install them with

`pip install -r requirements.txt`

first.

**Comment by anwarchk** [comment]
@mcowger I did complete that step from README and went through just fine. The next step of running it locally is the failing step.

**Comment by mcowger** [comment]
The error message given indicates that step did not complete successfully.  

Are you using `virtualenv`s?  Can we get some terminal output for the install of the requirements?

**Comment by anwarchk** [comment]
@mcowger Just updated my previous comment with console ouput

**Comment by anwarchk** [comment]
@mcowger just wondering if you or anyone from the team can help me with this issue. I would like to use this at the customer I am currently working on.

**Comment by montez-robinson** [comment]
@mcowger I'm having the same issue as well, using Cygwin on Win7:

$ pip install -r requirements.txt
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pytest (from -r requirements.txt (line 1))
  Using cached pytest-3.0.2-py2.py3-none-any.whl
Collecting mock (from -r requirements.txt (line 2))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting werkzeug (from -r requirements.txt (line 3))
  Using cached Werkzeug-0.11.11-py2.py3-none-any.whl
Collecting flask (from -r requirements.txt (line 4))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest->-r requirements.txt (line 1))
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting colorama (from pytest->-r requirements.txt (line 1))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting funcsigs>=1 (from mock->-r requirements.txt (line 2))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.9 (from mock->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->-r requirements.txt (line 2))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting click>=2.0 (from flask->-r requirements.txt (line 4))
  Using cached click-6.6.tar.gz
Collecting itsdangerous>=0.21 (from flask->-r requirements.txt (line 4))
  Using cached itsdangerous-0.24.tar.gz
Collecting Jinja2>=2.4 (from flask->-r requirements.txt (line 4))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.4->flask->-r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: py, colorama, pytest, funcsigs, six, pbr, mock, werkzeug, click, itsdangerous, MarkupSafe, Jinja2, flask
  Running setup.py install for click
  Running setup.py install for itsdangerous
  Running setup.py install for MarkupSafe
Successfully installed Jinja2-2.8 MarkupSafe-0.23 click-6.6 colorama-0.3.7 flask-0.11.1 funcsigs-1.0.2 itsdangerous-0.24 mock-2.0.0 pbr-1.10.0 py-1.4.31 pytest-3.0.2 six-1.10.0 werkzeug-0.11.11

$ python ./ephemerol/ephemerol-web.py
Traceback (most recent call last):
  File "./ephemerol/ephemerol-web.py", line 16, in <module>
    from flask import render_template, Flask, request, Response, flash
ImportError: No module named flask

**Comment by montez-robinson** [comment]
The script appears to work with Win Power Shell (Win7)
