### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by dkalemba** [Pivotal-Field-Engineering/ephemerol#8]
Running ephemerol requires the existence of a /tmp directory or you will receive FileIO errors when attempting to upload either a rules file or zip file.  Windows, for example, does not have this directory by default, so it must be created.

Very cool tool.

**Comment by cdelashmutt-pivotal** [comment]
Thanks!

This should now be resolved by 323be83d395bbfa8213c27e08ec28abfe079b153

Let us know if this doesn't resolve the issue.
